### ISSUE TITLE
Stomp ConnectFailedException

### ISSUE THREAD

**Issue by andy-maier** [zhmcclient/zhmc-log-forwarder#4]
Amber saw the following failure on VPC pod dal13z1.

This was seen with v20.10.1 of the ZaaS container build of the log forwarder (https://github.ibm.com/ZaaS/zhmc-log-forwarder/) which uses zhmc-log-forwarder 0.10.0 and zhmcclient 0.27.0.

```
dal13q2r133hmc1-log-forwarder.service - Daemon of zhmc-log-forwarder
    Loaded: loaded (/etc/systemd/system/dal13q2r133hmc1-log-forwarder.service, disabled)
    Active: active (running)
INFO: zhmc_log_forwarder starting
INFO: zhmc_log_forwarder version: 0.10.0
INFO: Config file: /etc/zhmc-log-forwarder/dal13q2r133hmc1_log_conf.yml
INFO: HMC log message file for CADF: /tmp/zhmc-log-forwarder-20.10.1/zhmc_log_forwarder/zhmc_log_messages.yml
INFO: HMC: 192.168.133.118, Userid: zaasmoni, Label: dal13q2r133hmc1
INFO: Since: now (2024-02-04 07:19:51.817766+00:00), Future: True
INFO: Forwarding: 'hmc log forwarding'; Logs: security, audit; Destination: syslog (server 127.0.0.1, port 514/udp, facility user); Format: cadf
INFO: Collecting these logs altogether: audit, security
dal13q2r350hmc1-log-forwarder.service - Daemon of zhmc-log-forwarder
    Loaded: loaded (/etc/systemd/system/dal13q2r350hmc1-log-forwarder.service, disabled)
    Active: active (running)
INFO: zhmc_log_forwarder starting
INFO: zhmc_log_forwarder version: 0.10.0
INFO: Config file: /etc/zhmc-log-forwarder/dal13q2r350hmc1_log_conf.yml
INFO: HMC log message file for CADF: /tmp/zhmc-log-forwarder-20.10.1/zhmc_log_forwarder/zhmc_log_messages.yml
INFO: HMC: 192.168.93.118, Userid: zaasmoni, Label: dal13q2r350hmc1
INFO: Since: now (2024-02-04 07:19:52.862602+00:00), Future: True
INFO: Forwarding: 'hmc log forwarding'; Logs: security, audit; Destination: syslog (server 127.0.0.1, port 514/udp, facility user); Format: cadf
INFO: Collecting these logs altogether: audit, security
INFO: Logging off from HMC
Traceback (most recent call last):
  File "/usr/local/bin/zhmc_log_forwarder", line 33, in <module>
    sys.exit(load_entry_point('zhmc-log-forwarder', 'console_scripts', 'zhmc_log_forwarder')())
  File "/tmp/zhmc-log-forwarder-20.10.1/zhmc_log_forwarder/zhmc_log_forwarder.py", line 1866, in main
    receiver = zhmcclient.NotificationReceiver(
  File "/usr/local/lib/python3.10/dist-packages/zhmcclient/_notification.py", line 178, in __init__
    self._conn.connect(self._userid, self._password, wait=True)
  File "/usr/local/lib/python3.10/dist-packages/stomp/connect.py", line 162, in connect
    Protocol11.connect(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/stomp/protocol.py", line 335, in connect
    self.transport.wait_for_connection()
  File "/usr/local/lib/python3.10/dist-packages/stomp/transport.py", line 321, in wait_for_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException
INFO: Logging off from HMC
Traceback (most recent call last):
  File "/usr/local/bin/zhmc_log_forwarder", line 33, in <module>
    sys.exit(load_entry_point('zhmc-log-forwarder', 'console_scripts', 'zhmc_log_forwarder')())
  File "/tmp/zhmc-log-forwarder-20.10.1/zhmc_log_forwarder/zhmc_log_forwarder.py", line 1866, in main
    receiver = zhmcclient.NotificationReceiver(
  File "/usr/local/lib/python3.10/dist-packages/zhmcclient/_notification.py", line 178, in __init__
    self._conn.connect(self._userid, self._password, wait=True)
  File "/usr/local/lib/python3.10/dist-packages/stomp/connect.py", line 162, in connect
    Protocol11.connect(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/stomp/protocol.py", line 335, in connect
    self.transport.wait_for_connection()
  File "/usr/local/lib/python3.10/dist-packages/stomp/transport.py", line 321, in wait_for_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException
```

**Comment by andy-maier** [comment]
From Amber:
Hi Andy, I have a finding about this issue. The problem won't happen if only starting one zhmc-log-forwarder instance in z-hw-logging container. It will happen when starting more than one zhmc-log-forwarder instances in z-hw-logging container. For example, DAL13 has pod z1 and z4, the problem will happen when starting one zhmc-log-forwarder for Z1 zhmc and Z4 zhmc respectively.
Can you pls help analyze the concurrent failure issue from code level?

**Comment by andy-maier** [comment]
PR #14 along with the changes in zhmcclient 1.16.0 should either solve the issue or if not then it provides better logging of what happens.
